[package]
name = "convertapitos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntex = { version = "1.0", features = ["tokio"] }
image = "0.24.8"
webp = "0.2"
serde = { version = "1.0.196", features = ["derive"] }
ntex-multipart = "1.0.0"
futures = "0.3"
env_logger = "0.11.3"

[dev-dependencies]
cargo-watch = "8.5.2"
