[package]
name = "convertapitos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
image = "0.25.1"
salvo = { version = "0.66.0", features = ["logging", "cors"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
webp = "0.2"
serde = { version = "1.0.196", features = ["derive"] }
validator = { version = "0.17.0", features = ["derive"] }
base64 = "0.22.0"

[dev-dependencies]
cargo-watch = "8.5.2"
