// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataErr } from "./DataErr";

export type AppResponse<T> = { data: T, error: DataErr | null, };
